apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ensae-mlops
spec:
  project: default
  source:
    repoURL: https://github.com/ENSAE-MSDS/MAP_DataScience.git
    targetRevision: master
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: user-maximerichaudeau1
  syncPolicy:
    automated:
      selfHeal: true