apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mapds-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - mapds-RI-NY-RA-DR.kub.sspcloud.fr
  rules:
  - host: mapds-RI-NY-RA-DR.kub.sspcloud.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mapds-service
            port:
              number: 80